<!--
   Informasion del
     _ ____   ____
    | |  _ \ / ___|
 _  | | |_) | |  _
| |_| |  __/| |_| |  _   _   _
 \___/|_|    \____| ( ) ( ) ( ) Cesar Hacker The Gray
                                                                                           
-->
<h1>Standard Data</h1>
[w] Gray : No header data found.<br />
FILE.FileName: Gray.jpg<br />
FILE.FileDateTime: 1539569245<br />
FILE.FileSize: 73387<br />
FILE.FileType: 2<br />
FILE.MimeType: image/jpeg<br />
FILE.SectionsFound: <br />
COMPUTED.html: width="640" height="640"<br />
COMPUTED.Height: 640<br />
COMPUTED.Width: 640<br />
COMPUTED.IsColor: 1<br />
<br><br>
<h1>Print All Information</h1>
<br><b>FILE</b> => <br/>&nbsp;<b>FileName</b> => Gray.jpg<br/>&nbsp;<b>FileDateTime</b> => 1539569245<br/>&nbsp;<b>FileSize</b> => 73387<br/>&nbsp;<b>FileType</b> => 2<br/>&nbsp;<b>MimeType</b> => image/jpeg<br/>&nbsp;<b>SectionsFound</b> => <br/><br><b>COMPUTED</b> => <br/>&nbsp;<b>html</b> => width="640" height="640"<br/>&nbsp;<b>Height</b> => 640<br/>&nbsp;<b>Width</b> => 640<br/>&nbsp;<b>IsColor</b> => 1<br/>
<!--
 ____                                  _ ____   ____
/ ___|  ___ __ _ _ __   ___ _ __      | |  _ \ / ___|
\___ \ / __/ _` | '_ \ / _ \ '__|  _  | | |_) | |  _
 ___) | (_| (_| | | | |  __/ |    | |_| |  __/| |_| |
|____/ \___\__,_|_| |_|\___|_|     \___/|_|    \____|
-->

